site_name: Unity Terrain Generation
site_url: https://ckempke.github.io/UnityTerrainGeneration/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Home: index.md
    - Theory:
        - Background: Background.md
        - Heightmaps or Voxels: heightmaps_and_voxels.md
        - World Size: size_of_game_worlds.md
        - Generation: generation.md
    - Practice:
        - Requirements: Requirements.md
        - Unity Terrains: unity-terrain-types.md
        - Locality Part1:
            - Overview: locality.md
            - Global:  global-loc.md
            - Global Features: mtns-and-valleys.md
            - Do-Over! Global Features: redo-mtns-and-valleys.md
            - Local : local-loc.md
        - Erosion: erosion-implementation.md
        - Performance: 
            - Overview: performance-1.md
            - Patch Management: runtime-patch-management.md
        - Biomes:
            - Overview: biomes.md
            - Water: water.md
            - Unity Notes: biomes-unity.md
        - Seeds: seeds.md
    - References: references.md
        
plugins:
    - search
    
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
   
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

